
start-at-login = true

[gaps]
inner.horizontal = 8
inner.vertical   = 8
outer.left       = 8
outer.right      = 8
outer.top        = 8
outer.bottom     = 8

[key-mapping]
preset = "qwerty"

[mode.main.binding]
# --- Window control ---
"alt+q" = "close"
"alt+m" = "minimize"

# --- Focus windows ---
"alt+h" = "focus left"
"alt+j" = "focus down"
"alt+k" = "focus up"
"alt+l" = "focus right"
"alt+shift+[" = "cycle-focus prev"
"alt+shift+]" = "cycle-focus next"

# --- Move windows ---
"alt+shift+h" = "move left"
"alt+shift+j" = "move down"
"alt+shift+k" = "move up"
"alt+shift+l" = "move right"
"alt+shift+return" = "promote"

# --- Stack windows ---
"alt+left"  = "stack left"
"alt+down"  = "stack down"
"alt+up"    = "stack up"
"alt+right" = "stack right"
"alt+;"     = "unstack"
"alt+["     = "cycle-stack prev"
"alt+]"     = "cycle-stack next"

# --- Resize ---
"alt+="            = "resize width +"
"alt+-"            = "resize width -"
"alt+shift+="      = "resize height +"
"alt+shift+-"      = "resize height -"

# --- Manipulate windows ---
"alt+t" = "toggle-floating"
"alt+f" = "toggle-fullscreen"

# --- WM options ---
"alt+shift+r" = "reapply-layout"
"alt+p"       = "toggle-pause"

# --- Layouts ---
"alt+x" = "flip-layout horizontal"
"alt+y" = "flip-layout vertical"

# --- Workspaces (Komorebi 0–7 → AeroSpace 1–8) ---
"alt+1" = "workspace 1"
"alt+2" = "workspace 2"
"alt+3" = "workspace 3"
"alt+4" = "workspace 4"
"alt+5" = "workspace 5"
"alt+6" = "workspace 6"
"alt+7" = "workspace 7"
"alt+8" = "workspace 8"

# --- Move windows across workspaces ---
"alt+shift+1" = "move-node-to-workspace 1"
"alt+shift+2" = "move-node-to-workspace 2"
"alt+shift+3" = "move-node-to-workspace 3"
"alt+shift+4" = "move-node-to-workspace 4"
"alt+shift+5" = "move-node-to-workspace 5"
"alt+shift+6" = "move-node-to-workspace 6"
"alt+shift+7" = "move-node-to-workspace 7"
"alt+shift+8" = "move-node-to-workspace 8"



